import {
  dehydrate,
  HydrationBoundary,
  QueryClient,
} from "@tanstack/react-query";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PropsWithChildren, cache } from "react";

import { Button, Header } from "../ui/components";
import SurggramAppProviders from "../SurggramAppProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SurgGram",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: PropsWithChildren) {
  const queryClient = new QueryClient();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SurggramAppProviders>
          <HydrationBoundary state={dehydrate(queryClient)}>
            <Header>
              <Header.Button>서버컴포넌트</Header.Button>
            </Header>
            {children}
            <Button color="primary" size="large" disabled>
              서버컴포넌트
            </Button>
          </HydrationBoundary>
        </SurggramAppProviders>
      </body>
    </html>
  );
}
